php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libjudydebian1 libjudy-dev
install: phpize
script: ./configure --with-judy=/usr && make && make test
